### PR TITLE
Add final build rh-ror50 for install_scl: 1

### PR DESCRIPTION
**Pull request by junaruga**
Hi,
I would like to add rh-ror50 build at the end of SCL builds, after actual work in SCL.

Thanks.

### CODE REVIEW

**Comment by pvalena** [comment]
LGTM

**Comment by junaruga** [comment]
hello, please merge it. Thanks.

**Comment by junaruga** [comment]
Please merge this PR, @hhorak

**Comment by omron93** [comment]
LGTM, merging.

**Pull request merged**
