### PR TITLE
Add recipes for rh-mongodb34, rh-mongodb32 and rh-mongodb30upg

### PR DESCRIPTION
**Pull request by omron93**
@junaruga Please take a look if I'm not missing any new feature. Thanks.

### CODE REVIEW

**Comment by junaruga** [comment]
@omron93 thanks for the PR. Let me check it tomorrow.
Have you tried to run your recipe file by RPM List Builder?

https://github.com/sclorg/rpm-list-builder

**Comment by junaruga** [comment]
@omron93 It looks good to me when taking a look at the recipe file manually.

**Comment by omron93** [comment]
Thanks.

> Have you tried to run your recipe file by RPM List Builder?

No. Collection is already built.

**Comment by junaruga** [comment]
@omron93 ok that's fine.

Because below command just verifies your created YAML data in your recipe file.
Just information for the future.

```
rpmlb /path/to/mongodb.yml rh-mongodb34
```

**Comment by omron93** [comment]
Thanks.

**Pull request merged**
