### PR TITLE
Add recipe for rh-mongodb36

### PR DESCRIPTION
**Pull request by khardix**
Build results: [sclo7-rh-mongodb36-rh-candidate](https://cbs.centos.org/koji/taginfo?tagID=1474)

### CODE REVIEW

**Comment by junaruga** [comment]
It looks good to me! Merged.

**Comment by omron93** [comment]
Only to note: rh-mongodb36 is only for RHEL7 (I think most of new collections too). So result for RHEL6 is "undefined".

Should be noted for every package that it's for RHEL7 only? Could be somehow possible to note this for whole collection?

**Comment by khardix** [comment]
@omron93 The `dist` tags with certain packages are leftovers from `rh-mongodb34` recipe. If the whole collection is el7 only, I think they can be dropped.

> Could be somehow possible to note this for whole collection?

No canonical way so far, IIRC. In this case, a comment could be enough, or we can propose a change to the recipe format.

Also to note: The `cmd` elements are "fixes" to the spec files I needed to make in order to make it buildable. Ideally, they should be merged upstream and then removed from the recipe.

**Comment by junaruga** [comment]
`dist` tag supports regular expression.
For example, you can set `dist: "el[67]"`, `dist: "el\d"` instead of `dist: "el7"` if you want

**Pull request merged**
